# The content of this file was generated by IBM Cloud
# Do not modify it as it might get overridden

from ibmcloudenv import IBMCloudEnv
from . import service_manager
from . import generate_password
IBMCloudEnv.init()



def initServices(app):
	
	return
